# Generated by Django 5.0.3 on 2024-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0007_tagpost_alter_women_cat_women_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagpost",
            name="step",
            field=models.CharField(blank=True, max_length=155),
        ),
    ]
