# Generated by Django 5.0.3 on 2024-05-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0012_uploadfiles_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Фото",
            ),
        ),
    ]
